name: CI Pipeline

on:
  push:
    branches:
      - master  # Change to your default branch if it's not 'main'
  pull_request:
    branches:
      - master  # Change to your default branch if it's not 'main'

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats  # Install Bats

      - name: Make script executable
        run: chmod +x family_script.sh  # Replace with your script name

      - name: Run tests
        run: bats test_script.bats  # Replace with your test file name
